---
title: "R Notebook"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r}
library("RCurl")
library("rpart")
library("rpart.plot")
library("randomForest")
library("FNN")
library("dplyr")    
library('repr')
library('ggplot2')
library("class")
library("e1071")
library("scales")  # for percentage scales
library("caret")

rain <- read.csv("RainfallPrediction.csv", header = TRUE)
summary(rain)
```

```{r}
rain <- rain[,2:23]

# factor character-columns
for (i in 1:ncol(rain)){
    if(is.character(rain[1,i])){
        rain[,i] = factor(rain[,i])
    }
}
```


```{r}
# remove NA values of the columns as desribed above
rain$MinTemp = replace(rain$MinTemp, is.na(rain$MinTemp), mean(rain$MinTemp, na.rm = TRUE))
rain$MaxTemp = replace(rain$MaxTemp, is.na(rain$MaxTemp), mean(rain$MaxTemp, na.rm = TRUE))

rain$Rainfall = replace(rain$Rainfall, is.na(rain$Rainfall), 0)

rain$Evaporation = replace(rain$Evaporation, is.na(rain$Evaporation), 0)

rain$Sunshine = replace(rain$Sunshine, is.na(rain$Sunshine), 0)

levels(rain$WindGustDir) <- c(levels(rain$WindGustDir), "NOWIND")
rain$WindGustDir[is.na(rain$WindGustDir)] <- 'NOWIND'

rain$WindGustSpeed = replace(rain$WindGustSpeed, is.na(rain$WindGustSpeed), 0)

levels(rain$WindDir9am) <- c(levels(rain$WindDir9am), "NOWIND")
rain$WindDir9am[is.na(rain$WindDir9am)] <- 'NOWIND'
levels(rain$WindDir3pm) <- c(levels(rain$WindDir3pm), "NOWIND")
rain$WindDir3pm[is.na(rain$WindDir3pm)] <- 'NOWIND'
                          
rain$WindSpeed9am = replace(rain$WindSpeed9am, is.na(rain$WindSpeed9am), 0)
rain$WindSpeed3pm = replace(rain$WindSpeed3pm, is.na(rain$WindSpeed3pm), 0)

rain$Humidity9am = replace(rain$Humidity9am, is.na(rain$Humidity9am), mean(rain$Humidity9am, na.rm = TRUE))
rain$Humidity3pm = replace(rain$Humidity3pm, is.na(rain$Humidity3pm), mean(rain$Humidity3pm, na.rm = TRUE))

rain$Pressure9am = replace(rain$Pressure9am, is.na(rain$Pressure9am), mean(rain$Pressure9am, na.rm = TRUE))
rain$Pressure3pm = replace(rain$Pressure3pm, is.na(rain$Pressure3pm), mean(rain$Pressure3pm, na.rm = TRUE))


rain$Cloud9am = replace(rain$Cloud9am, is.na(rain$Cloud9am), 0)
rain$Cloud3pm = replace(rain$Cloud3pm, is.na(rain$Cloud3pm), 0)

rain$Temp9am = replace(rain$Temp9am, is.na(rain$Temp9am), mean(rain$Temp9am, na.rm = TRUE))
rain$Temp3pm = replace(rain$Temp3pm, is.na(rain$Temp3pm), mean(rain$Temp3pm, na.rm = TRUE))

rain <- rain[!is.na(rain$RainToday),]

rain <- rain[!is.na(rain$RainTomorrow),]

summary(rain)
```


```{r}
locations = unique(rain$Location)

averageLocationRainfall = c()
index = 1
for (location in locations){
    averageLocationRainfall[index] = round(mean(subset(rain, rain$Location == location)$Rainfall), 2)
    index = index +1
}

# convert to dataframe
locationRainfalldf = data.frame(locations, averageLocationRainfall, stringsAsFactors=FALSE)

# graphs
options(repr.plot.width = 15, repr.plot.height = 15)  # plot size
#barplot(locationRainfalldf$averageLocationRainfall, 
#        names.arg = locationRainfalldf$locations, 
#        border = "steelblue",
#        main = "Average rainfall by location",
#        xlab = "rainfall(mm)",
#        las=1, 
#        horiz=TRUE)

ggplot(data = locationRainfalldf, 
        aes(x = locations, y = averageLocationRainfall),
        stat='identity', 
        position = 'dodge') + 
 geom_col() + 
 geom_text(aes(label = averageLocationRainfall), position = position_dodge(width=0.9), vjust=-0.25) +
 xlab("Locations") + 
 ylab("Average rainfall(mm)") +
 theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1, size = 18),
       axis.text.y = element_text(size = 20),
       axis.title.x = element_text(size = 30),
       axis.title.y = element_text(size = 30))
```


```{r}
ggplot(data = rain) +
  geom_point(mapping = aes(x = Pressure9am , y = Pressure3pm), alpha=0.3) +
ggtitle("Pressure9am and Pressure3pm")
```


```{r}
ggplot(data = rain) +
  geom_point(mapping = aes(x = Temp9am , y = Temp3pm), alpha=0.3) +
ggtitle("Temp9am and Temp3pm")
```
```{r}
```


```{r}
ggplot(rain, aes(x= Cloud9am,  group=RainToday)) + 
    geom_bar(aes(y = ..prop.., fill = factor(..x..)), stat="count") +
    geom_text(aes( label = scales::percent(..prop..),
                   y= ..prop.. ), stat= "count", vjust = -.5) +
    labs(y = "Percent", fill="Cloud Level") +
    facet_grid(~RainToday) +
    scale_y_continuous(labels = scales::percent)
```


```{r}
ggplot(rain, aes(x= Cloud3pm,  group=RainToday)) + 
    geom_bar(aes(y = ..prop.., fill = factor(..x..)), stat="count") +
    geom_text(aes( label = scales::percent(..prop..),
                   y= ..prop.. ), stat= "count", vjust = -.5) +
    labs(y = "Percent", fill="cloud level") +
    facet_grid(~RainToday) +
    scale_y_continuous(labels = scales::percent)
```


```{r}
NoNo <- percent(sum(rain$RainToday == "No" & rain$RainTomorrow == "No") / length(rain[,1]), accuracy = .001) 
YesYes <- percent(sum(rain$RainToday == "Yes" & rain$RainTomorrow == "Yes") / length(rain[,1]), accuracy = .001) 
NoYes <- percent(sum(rain$RainToday == "No" & rain$RainTomorrow == "Yes") / length(rain[,1]), accuracy = .001) 
YesNo <- percent(sum(rain$RainToday == "Yes" & rain$RainTomorrow == "No") / length(rain[,1]), accuracy = .001)

rainTodayTomorrow <- data.frame(
  group = c("NoYes", "YesYes", "NoNo", "YesNo"),
  value = c(NoYes, YesYes, NoNo, YesNo)
  )

rainTodayTomorrow
```

```{r}
rain_plot5 = data.frame(rain)
rain_plot5$Sunshine<-cut(rain_plot5$Sunshine, seq(0,16, 1), right=FALSE)

ggplot(rain_plot5)+ 
    geom_bar(mapping = aes(x= Sunshine, y= ..count.., fill = RainToday), 
             stat = "count", position = "fill")+
    labs(x = "Hours of sunshine", y="Percent")+
    scale_y_continuous(labels = scales::percent_format())
```


```{r}
# copy the data frame
rain_DT<-data.frame(rain)

num_samples = dim(rain_DT)[1]
set.seed(123)
sampling.rate = 0.8
training <- sample(1:num_samples, sampling.rate * num_samples, replace=FALSE)
trainingSet <- rain_DT[training, ]
testing <- setdiff(1:num_samples,training)
testingSet <- rain_DT[testing, ]

#Fit a decision tree model using the training data
decTreeModel <- rpart(RainTomorrow ~ .,data=trainingSet, method = "class")

#Plot the decision tree model
rpart.plot(decTreeModel)

# Find cp value to prevent overfitting
plotcp(decTreeModel)

# Based on the cp plot, we choose cp value =0.018
pruned_decTreeModel = prune(decTreeModel, cp=0.018)

# Plot the pruned decision tree model
rpart.plot(pruned_decTreeModel)
```


```{r}
predictedLabels<-predict(pruned_decTreeModel, testingSet, type = "class")
# Get the number of data points in the test set
sizeTestSet = dim(testingSet)[1]
# Get the number of data points that are misclassified
error = sum(predictedLabels != testingSet$RainTomorrow)
# Calculate the misclassification rate
accuracy_rate = 1-error/sizeTestSet
accuracy_rate


# Get the data points that are misclassified
IsWrong = (predictedLabels != testingSet$RainTomorrow)
# Get the data points that are classified as Happy or Sad
IsYes = (predictedLabels == 'Yes')
IsNo = (predictedLabels == 'No')
# Get the data points that are misclassified and are classified as Happy
IsWrongAndYes = (IsWrong & IsYes)
errorYes = sum(IsWrongAndYes)
IsWrongAndNo = (IsWrong & IsNo)
errorNo = sum(IsWrongAndNo)
# Calculate the misclassification rate
DT_misclassification_rate = (errorYes+errorNo)/sizeTestSet
DT_misclassification_rate 
# confusion matrix
DT_FN = confusionMatrix(predictedLabels, testingSet$RainTomorrow)
```


```{r}
RandForestModel <- randomForest(RainTomorrow ~ ., data = trainingSet, ntree=200, importance=TRUE)
plot(RandForestModel)
legend("top", colnames(RandForestModel$err.rate),fill=1:3)
RandForestModel$confusion

# Perform predictions for the testing set
predictedLabels<-predict(RandForestModel, testingSet)
# Get the number of data points in the test set
sizeTestSet = dim(testingSet)[1]
# Get the number of data points that are misclassified
error = sum(predictedLabels != testingSet$RainTomorrow)
# Calculate the misclassification rate
RF_misclassification_rate = error/sizeTestSet
RF_misclassification_rate
importance(RandForestModel)
varImpPlot(RandForestModel,type=1)

# confusion matrix
RF_FN = confusionMatrix(predictedLabels, testingSet$RainTomorrow)
```


```{r}
# copy the data frame
rain_LR<-data.frame(rain)

# k fold crossval
for (seed in c(123, 456, 666, 420, 888)){
    
    set.seed(seed)
    
    num_samples = dim(rain_LR)[1]
    sampling.rate = 0.8
    training <- sample(1:num_samples, sampling.rate * num_samples, replace=FALSE)
    trainingSet <- subset(rain_LR[training, ])
    testing <- setdiff(1:num_samples,training)
    testingSet <- subset(rain_LR[testing, ])

    LogisticReg <- glm(RainTomorrow ~ ., data = trainingSet, family = binomial(logit))
    predictions <-predict(LogisticReg, testingSet, type = "response")
    sizeTestSet = dim(testingSet)[1]
    predictedLabels= rep(0,sizeTestSet)
    predictedLabels=ifelse(predictions > 0.5,'Yes','No')
    error = sum(predictedLabels != testingSet$RainTomorrow)

    # Calculate the misclassification rate
    LR_misclassification_rate = error/sizeTestSet
    # Display the misclassification rate
    print(LR_misclassification_rate) # 
}




# use caret and compute a confusion matrix
LR_FN = confusionMatrix(data = as.factor(predictedLabels), reference = testingSet$RainTomorrow)
```


```{r}
# copy the data frame
rain_KNN<-data.frame(rain)

# normalize numeric column
for (i in 1: (ncol(rain_KNN)-1)){
    if(is.numeric(rain_KNN[1,i])){
        rain_KNN[,i] = (rain_KNN[,i] - mean(rain_KNN[,i])) / sd(rain_KNN[,i])
    }
  
}

# convert factor column to char
for (i in 1: (ncol(rain_KNN)-1)){
    if(is.factor(rain_KNN[1,i])){
        rain_KNN[,i] <- as.integer(rain_KNN[,i])
    }
  
}
summary(rain_KNN)


# Create Training and Testing Sets
set.seed(123)
num_samples = dim(rain_KNN)[1]
sampling.rate = 0.8
training <- sample(1:num_samples, sampling.rate * num_samples, replace=FALSE)
trainingSet <- subset(rain_KNN[training, ])
testing <- setdiff(1:num_samples,training)
testingSet <- subset(rain_KNN[testing, ])
# Get the features of the training set
trainingfeatures <- subset(trainingSet, select=c(-RainTomorrow))
# Get the labels of the training set
traininglabels <- trainingSet$RainTomorrow
# Get the features of the testing set
testingfeatures <- subset(testingSet, select=c(-RainTomorrow))
# Get the labels of the training set
testinglabels <- testingSet$RainTomorrow

for (i in 3:7){
    # call KNN
    predictedLabels = knn(trainingfeatures,testingfeatures,traininglabels,k=i)

    # Get the number of data points in the data set
    sizeTestSet = dim(testingSet)[1]
    # Get the number of data points that are misclassified
    error = sum(predictedLabels != testingSet$RainTomorrow)
    # Calculate the misclassification rate
    KNN_misclassification_rate = error/sizeTestSet
    # Display the misclassification rate
    print(i) # 
    print( KNN_misclassification_rate) # 
}

```


```{r}
# when k = 7, misclassification rate is the lowest

set.seed(123)
# call KNN
predictedLabels = knn(trainingfeatures,testingfeatures,traininglabels,k=7)

# Get the number of data points in the data set
sizeTestSet = dim(testingSet)[1]
# Get the number of data points that are misclassified
error = sum(predictedLabels != testingSet$RainTomorrow)
# Calculate the misclassification rate
KNN_misclassification_rate = error/sizeTestSet
# Display the misclassification rate

print( KNN_misclassification_rate) # 

KNN_FN = confusionMatrix(data = as.factor(predictedLabels), reference = testingSet$RainTomorrow)
```


